version: "3.5"
services:
  backend_1:
    image: httpd:latest
    container_name: apache2_server1
    volumes:
      - "/mnt/apache2/extra:/usr/local/apache2/conf/extra:ro"
      - "/mnt/apache2/htdocs:/usr/local/apache2/htdocs:ro"
    detach: true
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - vnet1

  backend_2:
    image: httpd:latest
    container_name: apache2_server2
    volumes:
      - "/mnt/apache2/extra:/usr/local/apache2/conf/extra:ro"
      - "/mnt/apache2/htdocs:/usr/local/apache2/htdocs:ro"
    detach: true
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - vnet1

networks:
  vnet1:
    driver: bridge
