- name: Install and Configuration Ansible
  become: true
  serial: 5
  hosts: ansible
  remote_user: azroot

  tasks:
    - name: Install Required Packages
      apt:
        name:
          - git
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Ansible & Docker's Package for Ansible-Galaxy
      pip:
        name:
          - docker
          - ansible
        state: present

    - name: Install Package via Ansible-Galaxy
      community.general.ansible_galaxy_install:
        type: collection
        name: community.docker

    - name: Clone Working Repository
      git:
        repo: https://github.com/DAChirkov/DevOps_Project_development.git
        dest: /home/temp/repo
        force: true

    - name: Create a New Directory
      file:
        path: /mnt/apache2
        state: directory
        mode: "0755"

    - name: Copy Configuration to the Folder
      copy:
        remote_src: yes
        directory_mode: yes
        src: /home/temp/repo/configuration/ansible
        dest: /etc
