- name: Installation and configuration Apache2
  gather_facts: true
  become: true
  serial: 5
  hosts: ansible
  remote_user: azroot
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Installing the Git package
      apt:
        name:
          - ansible
          - git
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Installing Docker's packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Installing package for "community.docker.docker_compose"
      pip:
        name:
          - docker
          - ansible-galaxy-collection
        state: present

    - name: Installing package "community.docker.docker_compose"
      community.general.galaxy_collection:
        name: community.docker
        state: present

    - name: Cloning repository
      git:
        repo: https://github.com/DAChirkov/DevOps_Project_development.git
        dest: /home/temp/repo
        force: true

    - name: Create a new directory
      file:
        path: /mnt/apache2
        state: directory
        mode: "0755"

    - name: Copy configuration to the folder
      copy:
        src: /home/temp/repo/configuration/ansible
        dest: /etc

    - name: Start configuring backend (Apache2) VMs
      command:
        sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azroot@vm-mng-1.eastus2.cloudapp.azure.com
        "ansible-playbook --ssh-common-args='-o StrictHostKeyChecking=no -i ~/.ssh/id_rsa' -i
        /etc/ansible/inventory.ini
        /etc/ansible/playbooks/apache2_test.yaml"
