- name: Installation and configuration Apache2
  gather_facts: true
  become: true
  serial: 5
  hosts: ansible
  remote_user: azroot

  tasks:
    - name: Install Base Packages
      apt:
        name:
          - ansible
          - git
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Installing Docker's Packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Install Docker's Package for Ansible-Galaxy
      pip:
        name:
          - docker
        state: present

    - name: Install Package via Ansible-Galaxy
      community.general.ansible_galaxy_install:
        type: collection
        name: community.docker

    - name: Clone Working Repository
      git:
        repo: https://github.com/DAChirkov/DevOps_Project_development.git
        dest: /home/temp/repo
        force: true

    - name: Create a New Directory
      file:
        path: /mnt/apache2
        state: directory
        mode: "0755"

    - name: Copy Configuration to the Folder
      copy:
        remote_src: yes
        directory_mode: yes
        src: /home/temp/repo/configuration/ansible
        dest: /etc

    - name: Start Configuring <backend (Apache2)> VMs
      shell:
        sudo ansible-playbook --ssh-common-args='-o StrictHostKeyChecking=no -i ~/.ssh/id_rsa' -i
        /etc/ansible/inventory.ini
        /etc/ansible/playbooks/apache2_test.yaml
