- name: Install and Configuration Servers
  gather_facts: true
  become: true
  serial: 5
  hosts: all
  remote_user: azroot

  tasks:
    - name: Install Git Package
      apt:
        name:
          - git
        state: present
        update_cache: yes

    - name: Clone Repository
      git:
        repo: https://github.com/DAChirkov/DevOps_Project_development.git
        dest: /home/temp/repo
        force: true

    - name: Install Required Packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Docker's Packages
      pip:
        name:
          - docker
          - docker_compose
        state: present
