- name: Configuring Apache2
  gather_facts: true
  become: true
  serial: 5
  hosts: backend
  remote_user: azroot

  tasks:
    - name: Create a New Directory
      file:
        path: /mnt/apache2
        state: directory
        mode: "0755"

    - name: Copy Configuration
      copy:
        remote_src: yes
        directory_mode: yes
        src: /home/temp/repo/configuration/apache2/
        dest: /mnt/apache2

    - name: Start Docker Containers
      shell: sudo docker compose -f /home/temp/repo/configuration/docker/apache2/docker-compose.yml up -d
