---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-v1
  labels:
    app: apache2
    env: production
spec:
  selector:
    matchLabels:
      project: azproject-v1
  template:
    metadata:
      labels:
        project: azproject-v1
    spec:
      containers:
        - name: apache2
          image: httpd:latest
          ports:
            - containerPort: 80
