apiVersion: v1
kind: A Helm chart for Kubernetes
metadata:
  name: deployment-v1
  labes:
    app: apache2
    env: production
spec:
  selector:
    matchLabels:
      project: azproject-v1
  template:
    metadata:
      labes:
        project: azproject-v1
    spec:
      containers:
        - name: apache2
          image: httpd:latest
          ports:
            - containerPort: 80
