name: Deploy an infrastructure to Azure via Terraform
on: 
  workflow_dispatch
env: 
    ROOT_PATH: '${{github.workspace}}/Terraform/Azure'
    ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

jobs:
  terraform:
    name: Terraform deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}} 

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ${{env.ROOT_PATH}} 