name: Azure - Preparing Ansible and deploying configs 
on:
  workflow_dispatch:      
  workflow_run:
    workflows:
      - "Azure - Deploying infrastructure via Terraform"
    types:
      - completed

env: 
    ROOT_PATH: '${{github.workspace}}/configuration/ansible'

jobs:
  ansible:
    name: Install Ansible and configuring VMs
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt update && sudo apt install -y openssh-client

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{secrets.AZURE_SSH_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Wait for 10 seconds
      run: sleep 10
        
    - name: Copy SSH privat-key to VM
      run: sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa
        ~/.ssh/id_rsa azroot@vm-mng-1.eastus2.cloudapp.azure.com:/home/azroot/.ssh/

    - name: Install Ansible Packages on Remote VM
      run: ansible-playbook --ssh-common-args='-o StrictHostKeyChecking=no -i ~/.ssh/id_rsa' -i
        ${{env.ROOT_PATH}}/inventory.ini
        ${{env.ROOT_PATH}}/playbooks/ansible.yaml

    - name: Starting to Configure Servers
      run: sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azroot@vm-mng-1.eastus2.cloudapp.azure.com
        "ansible-playbook --ssh-common-args='-o StrictHostKeyChecking=no -i ~/.ssh/id_rsa' -i
         /etc/ansible/inventory.ini
         /etc/ansible/playbooks/basic_conf.yaml" 
         
    - name: Start Preparing Servers (Apache2)
      run: sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azroot@vm-mng-1.eastus2.cloudapp.azure.com
        "ansible-playbook --ssh-common-args='-o StrictHostKeyChecking=no -i ~/.ssh/id_rsa' -i
        /etc/ansible/inventory.ini
        /etc/ansible/playbooks/srv_apache2.yaml"          
        
    # - name: Start configuring frontend (Nginx) VMs
    #   run: sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azroot@vm-mng-1.eastus2.cloudapp.azure.com
    #     "ansible-playbook --ssh-common-args='-o StrictHostKeyChecking=no -i ~/.ssh/id_rsa' -i
    #      /etc/ansible/inventory.ini
    #      /etc/ansible/playbooks/nginx_test.yaml"

     
    # - name: Start configuring frontend (Nginx) VMs
    #   run: sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azroot@vm-mng-1.eastus2.cloudapp.azure.com
    #     "ansible-playbook --ssh-common-args='-o StrictHostKeyChecking=no -i ~/.ssh/id_rsa' -i
    #      /etc/ansible/inventory.ini
    #      /etc/ansible/playbooks/nginx.yaml"

    # - name: Start configuring backend (Apache2) VMs
    #   run: sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azroot@vm-mng-1.eastus2.cloudapp.azure.com
    #     "ansible-playbook --ssh-common-args='-o StrictHostKeyChecking=no -i ~/.ssh/id_rsa' -i
    #      /etc/ansible/inventory.ini
    #      /etc/ansible/playbooks/apache2.yaml"
