name: Deploy an infrastructure to Azure via Terraform
on: 
  workflow_dispatch
env: 
    ROOT_PATH: '${{github.workspace}}/Terraform/Azure'
    ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

jobs:
  terraform_plan:
    name: Terraform pre-deploy
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}} 

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ${{env.ROOT_PATH}} 

  terraform_apply:
    name: Terraform deploy
    runs-on: ubuntu-latest
    needs: [terraform_plan]
    environment: production

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
  
      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
  
      - name: Terraform Init
        run: terraform init
        working-directory: ${{env.ROOT_PATH}} 
  
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{env.ROOT_PATH}} 

      - name: Get Terraform Outputs
        id: get_outputs
        run: |
          echo "::set-output name=resource_group_name::$(terraform output -raw resource_group_name)"
          echo "::set-output name=resource_virtual_network::$(terraform output -json resource_virtual_network)"
          echo "::set-output name=resource_subnet1::$(terraform output -json resource_subnet1)"
          echo "::set-output name=resource_subnet2::$(terraform output -json resource_subnet2)"
          echo "::set-output name=resource_subnet3::$(terraform output -json resource_subnet3)"
          echo "::set-output name=resource_main_nsg_name::$(terraform output -raw resource_main-nsg_name)"

      - name: Use Terraform Outputs
        run: |
          echo "Resource Group Name: ${{ steps.get_outputs.outputs.resource_group_name }}"
          echo "Resource Virtual Network: ${{ steps.get_outputs.outputs.resource_virtual_network }}"
          echo "Resource Subnet 1: ${{ steps.get_outputs.outputs.resource_subnet1 }}"
          echo "Resource Subnet 2: ${{ steps.get_outputs.outputs.resource_subnet2 }}"
          echo "Resource Subnet 3: ${{ steps.get_outputs.outputs.resource_subnet3 }}"
          echo "Resource Main NSG Name: ${{ steps.get_outputs.outputs.resource_main_nsg_name }}"
