name: Check Packages

on:
  workflow_dispatch:
    
jobs:
  Check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check versions
      run: |
         ansible --version
         docker --version
         docker compose version
